services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
      - ./nginx/fullchain3.pem:/etc/letsencrypt/live/ysahakyan.devopsaca.site/fullchain.pem
      - ./nginx/privkey3.pem:/etc/letsencrypt/live/ysahakyan.devopsaca.site/privkey.pem  
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  backend:
    build:
      context: flask
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    ports:
      - 9091:9091
